#
#
#

assistants:
  pete:
    how-to-with-driver: 'asst_a6thIShmnKwABWH8lgcduE0Z'
    how-to-without-driver: 'asst_uSipTRjks8LxWykJlRXWU5GO'
  driver.vision:
    tap: 'asst_nfQ7WB5j41W2lJ52Le3UGyb4'
    swipe: 'asst_0ULYI4yBDxPZUoRwYZxvK0fV'


spring:
  application.name: pete
  cloud:
    openfeign.client.config:
          default: &default
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
          test:
            <<: *default
            url: https://httpbin.org
          driver:
            <<: *default
            url: https://placeholder.com
          openai: &openai
            <<: *default
            url: https://api.openai.com
            defaultRequestHeaders:
              Authorization: Bearer ${SPRING_AI_OPENAI_API_KEY}
              OpenAI-Beta: assistants=v2
          openai-assistants:
            <<: *openai


logging:
  level:
    com.foreflight.genai.pete.client: debug

